name: Check
on:
  push:
    branches:
      - new

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
      uses: actions/checkout@v3

      - name: Install deps
      run: npm ci

      - name: Lint
      run: npm run lint

