name: Java CI with Maven

on:
  push:
    branches: [ "new" ]
  pull_request:
    branches: [ "new" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Copy artifacts
      run: cp target/SpaceLab_2_1.jar ${{ github.workspace }}/artifacts/SpaceLab_2_1.jar
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SpaceLab_2_1
        path: ${{ github.workspace }}/artifacts/SpaceLab_2_1.jar
    - name: Code style check
      run: mvn spotless:check
